remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: 号码助手
description: 免费彩票号码查询分析工具.
show_downloads: false
google_analytics: UA-347760-28



share_weiyun_url: https://play.google.com/store/apps/details?id=zc310.tech.rich.helper

